version: '2'

# official wekan docker-compos file: https://github.com/wekan/wekan/blob/main/docker-compose.yml

services:
  wekan-dingtalk-webhooks-proxy-server:
    image: wekan-dingtalk-webhooks-proxy-server
    build:
      context: ./wekan-dingtalk-webhooks-proxy-server
      dockerfile: Dockerfile
    container_name: wekan-dingtalk-webhooks-proxy-server
    restart: always
    networks:
      - wekan-tier
    volumes:
      - ./wekan-dingtalk-webhooks-proxy-server/config:/opt/wekan-dingtalk-webhooks-proxy-server/config

  wekan-db:
    image: mongo:4.2.7
    container_name: wekan-db
    restart: always
    command: mongod --logpath /dev/null --oplogSize 128 --quiet
    networks:
      - wekan-tier
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./data/wekan-db:/data/db
      - ./data/wekan-db-dump:/dump

  wekan:
    image: wekanteam/wekan:v5.83
    container_name: wekan
    restart: always
    networks:
      - wekan-tier
    ports:
      - 2080:8080
    environment:
      - MONGO_URL=mongodb://wekan-db:27017/wekan
      - ROOT_URL=http://127.0.0.1:2080  #   <=== using only at same laptop/desktop where Wekan is installed
      - MAIL_URL=smtp://<mail_url>:25/?ignoreTLS=true&tls={rejectUnauthorized:false}
      - MAIL_FROM=Wekan Notifications <noreply.wekan@mydomain.com>
      - WITH_API=true
      - RICHER_CARD_COMMENT_EDITOR=false
      - CARD_OPENED_WEBHOOK_ENABLED=false
      - BIGEVENTS_PATTERN=NONE
      - BROWSER_POLICY_ENABLED=true
    depends_on:
      - wekan-db

networks:
  wekan-tier:
    driver: bridge

